language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script: mvn clean source:jar deploy --settings travis_settings.xml

# travis encrypt -r bootique/bootique-jooq "CI_DEPLOY_USERNAME='name'"
# travis encrypt -r bootique/bootique-jooq "CI_DEPLOY_PASSWORD='password'"
env:
  global:
    - secure: "LMQZ18pgtNg/Cc6abd0u0RlwY2UYxu4vZvUOS50Ii1U4Fqq+dGmSZA3B0NhyWkVzs2YLIraUPpnsU57CCkbnXe0NptqlN021ujimDoocaNSQIfIBfWJyU0IQGhEkQMgCr05ZcF22m5PjErecnTCrJMOGW5MTa+SD0F0/m5ZxcL3vRdzRgzMNiqDt2NXxWN9YDmCt9/bfuvonlVkMFUJtPezGQ0SlrGyV/BrW5QJ1SkM5DbdFVxVlqvqVH21Mqn0xP7/xAioakELRN4Ll74+QDiZDd5Z+ohP3dKkpnDfxux/Uz5zH2W0Sv25sfkWSVmWc8+KkVymh+c45uRJh55uod6GEtrKGwX5nUo/Fa92xgxtC/E62hg/Ij+O1w68ckz6FJ958Vmlrbt9MC80rreqZCjkmxDORGW3wGagvSzsl50/kPCE4evjVqeZ5zIbBQnhir0QCqFO2DYph3bKfhTqGaAquDAXM93x5Hd42m4RQXeU1Iq8r+IOOfzTZcjnaGiajjQQRFH5b8EbXJtYUDHxn2a0yiOfSXTlkczQGB6RskwVn3V9ORddsKa7BFtOQ2CYMvOoDeghygeFu61z7sZthEPGrIkXSojwEBItGDM2YP1LLRf/NS7tn2GIrU2mDzXP8moBQjwZ6M3VfMHMrRPkI0E3YScrxC7glTTfwMNlkDls="
    - secure: "brQa6YSeOro16lJDO8lue4vaYlI/0O+yNBiP04OlUkJnNJuMEW4mrOcNzLEppUYlsr0sfM5usbIyQVgSTimf10ddENXTLQ+ZDSxjF75AJnEWHxQfsPcygk9Cta1lkNl8SwurdVb85BtQ6CRN3HTKjV8rRFWL/+m4nNZQRGG4uEw0+ZtGAf1lPbDCUiOwgGz7s9B9A4+LupcnWLIop5X+pEwp2C5LVrw+MaDc7V8FD4yK9FSYpOU1mJFwjOo1aflAImtBOUzU2i8kPAUztjRvLeWscQWwy1eMNgNgf7YHSl/hKPyS3qhOe/sidxv57cxRYdzVV0mwri0PphcUEZAFzcS/fLcmT0XHokGY58EcCFINXRtccbObCUoCi20IhKFABD8TunvPL6e7ayaMRlS2Mf41EzIvxZahH0+QOYy5Kwyrk0wNUZaboh47MJ5fpIfbCKXR7Z0tizgfuRxz8IQxgFbLAsWT7Mr8BpoBiSTTQ62CyPril2TpO/B9Ez8oiim4vjp5zYUkUGfELtnbNbz1E9CdfwjK+5BmlgkE7NlhByLCbcgAbQ7Di9WxwBUjTO+Nqw2VcBkKRuibvW58imxUPnzvcHSX54im2QO48XWJ8TlVgPQ92COPeWhCUovBCBnjmSTgsCw8rWOo3SlDdoZjDg9Sr28MzpdS0AL2oIFQJ+c="

